name: caller-workflow-cache

on: workflow_dispatch

jobs:
  job1:
    name: Create and Cache File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache hello.txt using hashFiles
        id: cache-step
        uses: actions/cache@v4
        with:
          path: mycache
          key: hello-cache-${{ hashFiles('mycache/hello.txt') }}

      - name: Create hello.txt
        run: |
          mkdir -p mycache
          echo "hello world, from me" > mycache/hello.txt

  job2:
    name: Retrieve and Use Cached File
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache hello.txt using hashFiles
        id: cache-step
        uses: actions/cache@v4
        with:
          path: mycache
          key: hello-cache-${{ hashFiles('mycache/hello.txt') }}

      - name: Show File Content
        run: |
          cat mycache/hello.txt
