name: caller-workflow-cache-env

on: workflow_dispatch

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-env.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment and install packages
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install requests pandas
          echo "Custom data for demo" > data.txt
          echo "Trained model placeholder" > model.pt

      - name: Cache entire environment
        id: cache-env
        uses: actions/cache@v4
        with:
          path: |
            .venv
            data.txt
            model.pt
          key: full-env-${{ hashFiles('**/data.txt', '**/model.pt') }}
          restore-keys: |
            full-env-

      - name: Show environment contents
        run: |
          ls -la
          source .venv/bin/activate
          pip list

  replicate-env:
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore environment from cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            data.txt
            model.pt
          key: full-env-${{ hashFiles('**/data.txt', '**/model.pt') }}
          restore-keys: |
            full-env-

      - name: Use cached environment
        run: |
          source .venv/bin/activate
          echo "Running with cached virtual environment..."
          python -c "import pandas as pd; print('Pandas version from cache:', pd.__version__)"
          echo "--- Contents of data.txt ---"
          cat data.txt
          echo "--- Contents of model.pt ---"
          cat model.pt
