name: caller-workflow-multiorg

on:
  workflow_dispatch
 # push:
  #  branches:
  #    - main
 # pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile C Code
        uses: BunnyOrg/Org-marketplace/actions/compile@main
        with:
          c_file: "src/sample.c"

      - name: Static Code Analysis
        uses: MyDummyorg159/actions-repo/.github/actions/static-analysis@main
        with:
          c_file: "src/sample.c"
