name: caller-workflow-cache-env

on: workflow_dispatch

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-env.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment and install packages
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install requests pandas
          echo "Custom data" > data.txt
          echo "Model checkpoint" > model.pt

      - name: Cache entire environment
        id: cache-env
        uses: actions/cache@v4
        with:
          path: |
            .venv
            data.txt
            model.pt
          key: full-env-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            full-env-

      - name: List environment contents
        run: |
          ls -la
          source .venv/bin/activate && pip list

  replicate-env:
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore environment from cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            data.txt
            model.pt
          key: full-env-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            full-env-

      - name: Validate replicated environment
        run: |
          ls -la
          source .venv/bin/activate && pip list
          cat data.txt
          cat model.pt
