name: caller-workflow-runner-based

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Choose the runner (ubuntu-latest or windows-latest)'
        required: true
        default: 'ubuntu-latest'

jobs:
  build-and-analyze:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile C Code
        uses: MyDummyorg159/actions-repo/.github/actions/compile-runner-based@main
        with:
          c_file: "src/sample.c"

      - name: Static Code Analysis
        uses: MyDummyorg159/actions-repo/.github/actions/static-analysis-runner-based@main
        with:
          c_file: "src/sample.c"
