name: caller-workflow-cache

on:
  workflow_dispatch:

jobs:
  generate-file:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate a unique cache key
        id: set-key
        run: echo "key=cache-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Create a text file
        run: |
          mkdir mycache
          echo "Hello from job 1!" > mycache/message.txt

      - name: Cache the file
        uses: actions/cache@v4
        with:
          path: mycache
          key: ${{ steps.set-key.outputs.key }}

  read-file:
    runs-on: ubuntu-latest
    needs: generate-file
    steps:
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: ${{ needs.generate-file.outputs.cache-key }}

      - name: Display file content
        run: cat mycache/message.txt
