name: caller-workflow-cache

on:
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create seed file to ensure hashFiles works
        run: |
          mkdir -p mycache
          echo "seed file" > mycache/seed.txt

      - name: Cache files (key based on seed.txt)
        id: cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: multi-file-cache-${{ hashFiles('mycache/seed.txt') }}

      - name: Generate .txt files if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "File1 at $(date)" > mycache/file1.txt
          echo "File2 at $(date)" > mycache/file2.txt
          echo "File3 at $(date)" > mycache/file3.txt

  read-files:
    runs-on: ubuntu-latest
    needs: generate-files
    steps:
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: ${{ needs.generate-files.outputs.cache-key }}

      - name: Print cached file contents
        run: |
          echo "Cached files:"
          ls -l mycache
          for file in mycache/*.txt; do
            echo "--- $file ---"
            cat "$file"
            echo ""
          done
