name: caller-workflow-cache

on:
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create files and cache them
        id: cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: multi-file-cache-${{ hashFiles('mycache/*.txt') }}

      - name: Generate files if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p mycache
          echo "Generated at $(date)" > mycache/file1.txt
          echo "Hello again at $(date)" > mycache/file2.txt
          echo "Some dynamic content" > mycache/file3.txt

  read-files:
    runs-on: ubuntu-latest
    needs: generate-files
    steps:
      - name: Restore cached files
        uses: actions/cache@v4
        with:
          path: mycache
          key: ${{ needs.generate-files.outputs.cache-key }}

      - name: Print .txt contents
        run: |
          echo "Listing contents of mycache:"
          ls -l mycache
          echo ""
          for file in mycache/*.txt; do
            echo "--- $file ---"
            cat "$file"
            echo ""
          done
