name: caller-workflow-cache

on:
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dummy file (only needed first run)
        run: mkdir -p mycache && echo "stub" > mycache/.init.txt

      - name: Cache using hashFiles
        id: cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: multi-file-cache-${{ hashFiles('mycache/*.txt') }}

      - name: Generate .txt files if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Generated at $(date)" > mycache/file1.txt
          echo "Another at $(date)" > mycache/file2.txt
          echo "Dynamic stuff" > mycache/file3.txt

  read-files:
    runs-on: ubuntu-latest
    needs: generate-files
    steps:
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: ${{ needs.generate-files.outputs.cache-key }}

      - name: Display contents
        run: |
          echo "Cached files:"
          ls -l mycache
          for file in mycache/*.txt; do
            echo "--- $file ---"
            cat "$file"
            echo ""
          done
