name: caller-workflow-cache

on:
  workflow_dispatch:

jobs:
  generate-files:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and cache files
        id: cache
        uses: actions/cache@v4
        with:
          path: mycache
          key: multi-file-cache-${{ github.run_id }}
        continue-on-error: true # avoid failure if cache already exists

      - name: Create dynamic .txt files
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p mycache
          echo "Generated at $(date)" > mycache/file1.txt
          echo "Hello world at $(date)" > mycache/file2.txt
          echo "Dynamic cache content" > mycache/file3.txt

  read-files:
    runs-on: ubuntu-latest
    needs: generate-files
    steps:
      - name: Restore cached files
        uses: actions/cache@v4
        with:
          path: mycache
          key: ${{ needs.generate-files.outputs.cache-key }}

      - name: Print contents of all .txt files
        run: |
          echo "Listing files:"
          ls -l mycache
          echo "Displaying file contents:"
          for file in mycache/*.txt; do
            echo "--- $file ---"
            cat "$file"
            echo ""
          done
