name: C Code Compilation and Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-reusable-workflow:
    uses: MyDummyorg159/workflow-templates/.github/workflows/template.yml@main
    with:
      c_file: "sample.c"
      cppcheck_options: "--enable=all"
