name: Reusable Workflow A

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Running Reusable Workflow A with name: ${{ inputs.name }}"'
